apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-webcolor
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/fch-bsp/k8s-web-color-page.git
    targetRevision: HEAD
    path: k8s # monitorando de 3 em 3 minutos 
  destination: 
    server: https://kubernetes.default.svc
    namespace: webcolor

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    # automated:
    #   selfHeal: false
    #   prune: false