apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-manifesto
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/fch-bsp/argo-manifests.git
    targetRevision: HEAD
    path: k8s # monitorando de 3 em 3 minutos 
  destination: 
    server: https://kubernetes.default.svc
    namespace: argo-manifesto

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    # automated:
    #   selfHeal: false
    #   prune: false